### ISSUE TITLE
router 动画，from和to路由会同时显示

### ISSUE THREAD

**Issue by ColMugX** [react-component/queue-anim#52]
做法按照 example router 的做法去做，几乎没有改变。

效果是：from 在做离场动画的同时，to 在做进场动画。

问题是：to 路由会因为 from 路由的高度被压在下面，必须等到 from 完成离场删除节点之后，to 路由恢复位置。从而导致每次转场 to 都会有位移。

请问如何解决？谢谢。

**Comment by ColMugX** [comment]
设置`delay`的话，to 会延迟，但 from 会等到 to 做完动画才消失..

**Comment by jljsj33** [comment]
```css
.你的样式.queue-anim-leaving {
    position: absolute;
    top: 0;
    width: 100%;
} 
```
