### ISSUE TITLE
出场动画关闭后，更新节点动画失效。

### ISSUE THREAD

**Issue by nuintun** [react-component/queue-anim#57]
LESS:

```less
.ui-box {
  margin-top: 10px;
  margin-left: 11px;
}
.ui-box {
  > div {
    width: 100px;
    height: 50px;
    text-align: center;
    line-height: 50px;
    margin-left: -1px;
    border: 1px solid red;
    display: inline-block;
  }
}
```

JSX:
```jsx
import React from 'react';
import ReactDOM from 'react-dom';
import QueueAnim from 'rc-queue-anim';

const list = [
  [
    <div key="1">依次进入1</div>,
    <div key="2">依次进入2</div>,
    <div key="3">依次进入3</div>,
    <div key="4">依次进入4</div>,
    <div key="5">依次进入5</div>
  ],
  [
    <div key="6">依次进入6</div>,
    <div key="7">依次进入7</div>,
    <div key="8">依次进入8</div>,
    <div key="9">依次进入9</div>,
    <div key="10">依次进入10</div>
  ]
];

class App extends React.Component {
  state = {
    id: 0,
    list: [...list[0]]
  };

  handleClick = () => {
    const id = this.state.id === 0 ? 1 : 0;

    this.setState({ id, list: [...list[id]] });
  };

  render() {
    return (
      <>
        <button onClick={this.handleClick} style={{ marginTop: 10, marginLeft: 10 }}>
          切换列表
        </button>
        <QueueAnim type="bottom" className="ui-box" interval={[100, 0]} duration={[450, 0]}>
          {this.state.list}
        </QueueAnim>
      </>
    );
  }
}

ReactDOM.render(<App />, document.getElementById('app'));
```

关闭出场动画，切换新节点入场动画会消失，粗略看了下代码应该是出场动画关闭后并未触发正常情况下的出场逻辑处理，保存了以前的状态值，所以必须设置 `forcedReplay` 才正常（入场动画关闭估计也存在类似问题）。
